#!/bin/sh

set -x

if [ ! -e "$HOME/.config" ]; then
	mkdir "$HOME"/.config
fi

for dir in w3m newsboat; do
	ln -s "$PWD"/config/$dir "$HOME"/.config/$dir
done

if [ ! -e "$HOME/.local" ]; then
	mkdir "$HOME"/.local
fi

if [ ! -e "$HOME/.local/bin/" ]; then
	mkdir "$HOME"/.local/bin
fi

ln -s "$PWD"/scripts "$HOME"/.local/bin/scripts

for file in .bashrc .exrc .profile .tmux.conf; do
	ln -s "$PWD"/$file "$HOME"/$file
done
