#!/bin/sh

set -xe

if [ ! -e "$HOME/.config" ]; then
	mkdir "$HOME"/.config
fi

for dir in sway w3m waybar; do
	ln -s config/$dir "$HOME"/.config/$dir
done

if [ ! -e "$HOME/.local/bin/" ]; then
	mkdir $HOME/.local
	mkdir $HOME/.local/bin
fi

ln -s scripts "$HOME"/.local/bin/scripts

for file in .bashrc .exrc .profile .tmux.conf; do
	ln -s $file "$HOME"/$file
done
