#!/bin/sh

set -x

if [ ! -d "$HOME"/.config ]; then
	mkdir "$HOME"/.config
fi

for dir in w3m newsboat; do
	ln -s "$PWD"/config/$dir "$HOME"/.config/$dir || echo "$dir directory exists"
done

if [ ! -d "$HOME/.local/bin/" ]; then
	mkdir -p "$HOME"/.local/bin
fi

ln -s "$PWD"/scripts "$HOME"/.local/bin/scripts || echo "Scripts directory already exists"

for file in .bashrc .exrc .profile .tmux.conf .gitconfig; do
	if [ -e "$HOME"/$file ]; then
		mv "$HOME"/$file "$HOME"/$file.bak
	fi
	ln -s "$PWD"/$file "$HOME"/$file
done
