#!/usr/local/bin/perl

use warnings;
use strict;

#my $time = localtime;

use POSIX qw(strftime);
my $time = strftime "%a %b %e %H:%M %Y", localtime;

# apm -ablt displays 
# AC-line status 0: off-line, 1: on-line, 2: backup power
# Battery status 0,1,2,3 "high", "low", "critical", "charging" respectivly
# Remaining battery percentage. 225 if fuction not supported
# Estimated battery lifetime in seconds

my $batinfo = `/usr/sbin/apm -ablt`;
my ( $ac_status, $bat_status, $bat_percent, $bat_lifetime ) = split "\n", $batinfo;

if ($ac_status eq "1") {
    printf("$time  Bat: Charging");
    exit;
}

printf("$time Bat: $bat_percent/100");
